### ISSUE TITLE
license file please

### ISSUE THREAD

**Issue by windbender** [sonus21/monitoring#1]
Can you add a license file to this project please ?  :-)

I'm unable to use it in my project without ability to understand how it's licensed.

one of your dependencies uses Apache 2.0:

https://github.com/renatoathaydes/javanna/blob/master/LICENSE.txt

Perhaps that's appropriate ?

**Comment by sonus21** [comment]
Hello
I have added a license file, I don't think you can use this as it as. you would need to alter some code or take some of the classes and use in your application.

**Comment by windbender** [comment]
awesome thanks.  I did modify the code, of course!   But if it had been GPL licensed this would not have been possible.   Thanks!!
